# Generated by Django 5.1.2 on 2024-11-03 17:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('call', '0001_initial'),
        ('number', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='call',
            name='call_id',
        ),
        migrations.RemoveField(
            model_name='call',
            name='timestamp',
        ),
        migrations.RemoveField(
            model_name='call',
            name='type',
        ),
        migrations.AlterField(
            model_name='call',
            name='destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='destination', to='number.number'),
        ),
        migrations.AlterField(
            model_name='call',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='source', to='number.number'),
        ),
        migrations.CreateModel(
            name='CallRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('START', 'START'), ('END', 'END')], default='START', max_length=6)),
                ('timestamp', models.DateTimeField()),
                ('call_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='call.call')),
            ],
        ),
    ]
