# Generated by Django 5.1.2 on 2024-11-04 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('call', '0002_remove_call_call_id_remove_call_timestamp_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='callregister',
            old_name='call_id',
            new_name='call',
        ),
    ]
